import { useEffect, useState } from "react";
import SectionCard from "./SectionCard";

/** Build a clean plain-text version of the manual for download. */
function buildTextContent(manual, totalMarks) {
  const line = (char = "=", len = 60) => char.repeat(len);
  const section = (title) => `\n${line()}\n  ${title}\n${line()}\n`;

  const rows = [
    line("="),
    "  LabGenie AI — Lab Manual",
    line("="),
    `  Subject    : ${manual.meta?.subject || "—"}`,
    `  Topic      : ${manual.meta?.topic || "—"}`,
    `  Difficulty : ${manual.meta?.difficulty || "—"}`,
    line("-"),
    "",
  ];

  rows.push(section("1. AIM"));
  rows.push(manual.aim || "");

  rows.push(section("2. THEORY"));
  rows.push(manual.theory || "");

  rows.push(section("3. REQUIREMENTS"));
  (manual.requirements || []).forEach((item, i) => {
    rows.push(`  ${i + 1}. ${item}`);
  });

  rows.push(section("4. PROCEDURE"));
  (manual.procedure || []).forEach((step, i) => {
    const clean = step.replace(/^\d+[\.\)]\s*/, "");
    rows.push(`  ${i + 1}. ${clean}`);
  });

  rows.push(section("5. CODE"));
  rows.push(manual.code || "");

  rows.push(section("6. EXPECTED OUTPUT"));
  rows.push(manual.expectedOutput || "");

  rows.push(section("7. PRECAUTIONS"));
  (manual.precautions || []).forEach((item, i) => {
    rows.push(`  ${i + 1}. ${item}`);
  });

  rows.push(section("8. VIVA QUESTIONS"));
  (manual.vivaQuestions || []).forEach((qa, i) => {
    rows.push(`  Q${i + 1}. ${qa.question}`);
    rows.push(`  A.  ${qa.answer}`);
    rows.push("");
  });

  rows.push(section("9. EVALUATION RUBRIC"));
  rows.push(`  ${"Criterion".padEnd(50)} Marks`);
  rows.push(`  ${line("-", 56)}`);

  (manual.evaluationRubric || []).forEach((row) => {
    rows.push(`  ${row.criterion.padEnd(50)} ${row.marks}`);
  });

  rows.push(`  ${line("-", 56)}`);
  rows.push(`  ${"TOTAL".padEnd(50)} ${totalMarks}`);

  rows.push("\n" + line("="));
  rows.push("  Generated by LabGenie AI — IBM SkillsBuild / AICTE Internship");
  rows.push(line("=") + "\n");

  return rows.join("\n");
}

/** Download manual as a text file. */
function downloadManual(manual, totalMarks) {
  const content = buildTextContent(manual, totalMarks);

  const filename =
    "LabGenie-" +
    (manual.meta?.topic || "Manual")
      .replace(/[^a-zA-Z0-9 _-]/g, "")
      .trim()
      .replace(/\s+/g, "-") +
    ".txt";

  const blob = new Blob([content], {
    type: "text/plain;charset=utf-8",
  });

  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");

  a.href = url;
  a.download = filename;
  a.click();

  URL.revokeObjectURL(url);
}

function LabManualResults({ manual }) {
  const [activeSection, setActiveSection] = useState("aim");

  // Always open the newly generated manual from the beginning.
  useEffect(() => {
    if (manual) {
      setActiveSection("aim");
    }
  }, [manual]);

  if (!manual) {
    return (
      <section className="manual-empty-workspace">
        <div className="empty-state">
          <div className="empty-state-icon">📋</div>

          <div>
            <strong>Your lab manual is waiting</strong>

            <p>
              Generate an experiment above and your complete laboratory
              manual will appear here.
            </p>

            <span className="empty-state-hint">
              Try: Data Structures → Bubble Sort Algorithm
            </span>
          </div>
        </div>
      </section>
    );
  }

  const totalMarks = manual.evaluationRubric
    ? manual.evaluationRubric.reduce(
        (sum, row) => sum + Number(row.marks || 0),
        0
      )
    : 0;

  const sections = [
    {
      id: "aim",
      number: "01",
      label: "Aim",
      shortLabel: "Overview",
      icon: "🎯",
    },
    {
      id: "theory",
      number: "02",
      label: "Theory",
      shortLabel: "Concept",
      icon: "📖",
    },
    {
      id: "requirements",
      number: "03",
      label: "Requirements",
      shortLabel: "Setup",
      icon: "🛠",
    },
    {
      id: "procedure",
      number: "04",
      label: "Procedure",
      shortLabel: "Steps",
      icon: "📝",
    },
    {
      id: "code",
      number: "05",
      label: "Code",
      shortLabel: "Implementation",
      icon: "💻",
    },
    {
      id: "output",
      number: "06",
      label: "Expected Output",
      shortLabel: "Result",
      icon: "✅",
    },
    {
      id: "precautions",
      number: "07",
      label: "Precautions",
      shortLabel: "Safety",
      icon: "⚠️",
    },
    {
      id: "viva",
      number: "08",
      label: "Viva Questions",
      shortLabel: "Practice",
      icon: "❓",
    },
    {
      id: "rubric",
      number: "09",
      label: "Evaluation",
      shortLabel: "Assessment",
      icon: "📊",
    },
  ];

  const currentIndex = sections.findIndex(
    (section) => section.id === activeSection
  );

  const currentSection = sections[currentIndex];

  function goPrevious() {
    if (currentIndex > 0) {
      setActiveSection(sections[currentIndex - 1].id);
    }
  }

  function goNext() {
    if (currentIndex < sections.length - 1) {
      setActiveSection(sections[currentIndex + 1].id);
    }
  }

  return (
    <section className="manual-workspace">

      {/* ─────────────────────────────────────────────
          MANUAL HEADER
      ───────────────────────────────────────────── */}
      <div className="manual-topbar">
        <div className="manual-heading">
          <div className="workspace-label">
            <span className="workspace-dot" />
            GENERATED LAB MANUAL
          </div>

          <h2>{manual.meta?.topic || "Laboratory Experiment"}</h2>

          <p className="manual-subtitle">
            {manual.meta?.subject || "Subject"}
            <span>•</span>
            {manual.meta?.difficulty || "Intermediate"} level
          </p>
        </div>

        <button
          className="manual-download"
          onClick={() => downloadManual(manual, totalMarks)}
        >
          <span>↓</span>
          Download
        </button>
      </div>

      {/* ─────────────────────────────────────────────
          MANUAL INFO STRIP
      ───────────────────────────────────────────── */}
      <div className="manual-info-grid">

        <div className="manual-info-card">
          <div className="manual-info-icon blue">
            ✦
          </div>

          <div>
            <span className="manual-info-label">AI ENGINE</span>
            <strong>IBM Granite</strong>
            <small>AI-generated manual</small>
          </div>
        </div>

        <div className="manual-info-card">
          <div className="manual-info-icon purple">
            ⌕
          </div>

          <div>
            <span className="manual-info-label">KNOWLEDGE</span>
            <strong>
              {manual.meta?.ragEnabled ? "RAG Enhanced" : "AI Generated"}
            </strong>

            <small>
              {manual.meta?.ragEnabled &&
              manual.meta?.retrievedSources?.length > 0
                ? manual.meta.retrievedSources.join(", ")
                : "Curated lab knowledge"}
            </small>
          </div>
        </div>

        <div className="manual-info-card">
          <div className="manual-info-icon teal">
            ✓
          </div>

          <div>
            <span className="manual-info-label">MANUAL STATUS</span>
            <strong>Complete</strong>
            <small>9 sections ready</small>
          </div>
        </div>

        <div className="manual-info-card">
          <div className="manual-info-icon amber">
            ★
          </div>

          <div>
            <span className="manual-info-label">ASSESSMENT</span>
            <strong>{totalMarks} Marks</strong>
            <small>Evaluation rubric included</small>
          </div>
        </div>

      </div>

      {/* ─────────────────────────────────────────────
          MAIN MANUAL AREA
      ───────────────────────────────────────────── */}
      <div className="manual-layout">

        {/* LEFT SIDEBAR */}
        <aside className="manual-sidebar">

          <div className="sidebar-heading">
            <span>LAB MANUAL</span>
            <span className="sidebar-count">
              {sections.length}
            </span>
          </div>

          <p className="sidebar-subtitle">
            Navigate through your experiment
          </p>

          <div className="section-nav">
            {sections.map((section) => (
              <button
                key={section.id}
                className={`section-nav-item ${
                  activeSection === section.id ? "active" : ""
                }`}
                onClick={() => setActiveSection(section.id)}
              >
                <span className="section-nav-number">
                  {section.number}
                </span>

                <span className="section-nav-icon">
                  {section.icon}
                </span>

                <span className="section-nav-text">
                  <strong>{section.label}</strong>
                  <small>{section.shortLabel}</small>
                </span>

                {activeSection === section.id && (
                  <span className="section-nav-arrow">→</span>
                )}
              </button>
            ))}
          </div>

          <div className="sidebar-tip">
            <span>✦</span>
            <div>
              <strong>AI Generated</strong>
              <small>
                Your manual was created using IBM Granite.
              </small>
            </div>
          </div>

        </aside>

        {/* RIGHT CONTENT */}
        <div className="manual-content">

          <div className="manual-content-header">
            <div>
              <span className="manual-section-number">
                SECTION {currentSection.number}
              </span>

              <h3>
                {currentSection.icon} {currentSection.label}
              </h3>
            </div>

            <span className="manual-progress">
              {currentIndex + 1} of {sections.length}
            </span>
          </div>

          {/* AIM */}
          {activeSection === "aim" && (
            <SectionCard icon="🎯" title="Aim" accent="blue">
              <p className="section-text">{manual.aim}</p>
            </SectionCard>
          )}

          {/* THEORY */}
          {activeSection === "theory" && (
            <SectionCard icon="📖" title="Theory" accent="blue">
              <p className="section-text">{manual.theory}</p>
            </SectionCard>
          )}

          {/* REQUIREMENTS */}
          {activeSection === "requirements" && (
            <SectionCard icon="🛠" title="Requirements" accent="purple">
              <ul className="section-list">
                {(manual.requirements || []).map((item, i) => (
                  <li key={i}>
                    <span className="list-dot" />
                    {item}
                  </li>
                ))}
              </ul>
            </SectionCard>
          )}

          {/* PROCEDURE */}
          {activeSection === "procedure" && (
            <SectionCard icon="📝" title="Procedure" accent="teal">
              <div className="section-list procedure-list">
                {(manual.procedure || []).map((step, i) => (
                  <div key={i} className="procedure-step">
                    <span className="list-num">{i + 1}</span>

                    <span>
                      {step.replace(/^\d+[\.\)]\s*/, "")}
                    </span>
                  </div>
                ))}
              </div>
            </SectionCard>
          )}

          {/* CODE */}
          {activeSection === "code" && (
            <SectionCard icon="💻" title="Code" accent="blue">
              <div className="code-block">
                <pre>{manual.code}</pre>
              </div>
            </SectionCard>
          )}

          {/* OUTPUT */}
          {activeSection === "output" && (
            <SectionCard icon="✅" title="Expected Output" accent="blue">
              <div className="output-block">
                <pre>{manual.expectedOutput}</pre>
              </div>
            </SectionCard>
          )}

          {/* PRECAUTIONS */}
          {activeSection === "precautions" && (
            <SectionCard icon="⚠️" title="Precautions" accent="amber">
              <ul className="section-list">
                {(manual.precautions || []).map((item, i) => (
                  <li key={i}>
                    <span
                      className="list-dot"
                      style={{ background: "var(--amber)" }}
                    />
                    {item}
                  </li>
                ))}
              </ul>
            </SectionCard>
          )}

          {/* VIVA */}
          {activeSection === "viva" && (
            <SectionCard icon="❓" title="Viva Questions" accent="indigo">
              <div className="viva-list">
                {(manual.vivaQuestions || []).map((qa, i) => (
                  <div key={i} className="viva-item">
                    <div className="viva-question">
                      <span className="viva-q-label">
                        Q{i + 1}.
                      </span>

                      {qa.question}
                    </div>

                    <div className="viva-answer">
                      <span className="viva-a-label">A.</span>
                      {qa.answer}
                    </div>
                  </div>
                ))}
              </div>
            </SectionCard>
          )}

          {/* RUBRIC */}
          {activeSection === "rubric" && (
            <SectionCard
              icon="📊"
              title="Evaluation Rubric"
              accent="green"
            >
              <table className="rubric-table">
                <thead>
                  <tr>
                    <th>Criterion</th>
                    <th>Marks</th>
                  </tr>
                </thead>

                <tbody>
                  {(manual.evaluationRubric || []).map((row, i) => (
                    <tr key={i}>
                      <td>{row.criterion}</td>

                      <td>
                        <span className="marks-badge">
                          {row.marks}
                        </span>
                      </td>
                    </tr>
                  ))}

                  <tr className="total-row">
                    <td>Total</td>

                    <td>
                      <span className="marks-badge">
                        {totalMarks}
                      </span>
                    </td>
                  </tr>
                </tbody>
              </table>
            </SectionCard>
          )}

          {/* ─────────────────────────────────────────
              PREVIOUS / NEXT
          ───────────────────────────────────────── */}
          <div className="manual-pagination">

            <button
              className="manual-page-btn"
              disabled={currentIndex === 0}
              onClick={goPrevious}
            >
              ← Previous
            </button>

            <div className="manual-page-progress">
              <div className="manual-progress-track">
                <div
                  className="manual-progress-fill"
                  style={{
                    width: `${((currentIndex + 1) / sections.length) * 100}%`,
                  }}
                />
              </div>

              <span>
                Section {currentIndex + 1} / {sections.length}
              </span>
            </div>

            <button
              className="manual-page-btn"
              disabled={currentIndex === sections.length - 1}
              onClick={goNext}
            >
              Next →
            </button>

          </div>

        </div>
      </div>
    </section>
  );
}

export default LabManualResults;